### ISSUE TITLE
proper error handling (express / userfacing)

### ISSUE THREAD

**Issue by kuzyn** [n10as/n20.as#12]
Review our error handling both in express (controllers + models)

### homeworks

https://www.loggly.com/blog/node-js-error-handling/

http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events

**Comment by aconanlai** [comment]
https://github.com/nodejs/node/issues/830

**Comment by kuzyn** [comment]
Things looks okay atm. Let's close this & raise another issue if we see problems. No need to have custom errors at this point, and we can wait till after the cms is done to review our error codes
