### ISSUE TITLE
plug in travis

### ISSUE THREAD

**Issue by kuzyn** [n10as/n20.as#17]
Okay, this is the step-up from just having our mocha tests available. Travis will essentially build our app, run our tests & report mocha errors from our repo's commits. This way we don't have to run all the tests locally on push (maybe just the basis, i.e. roughly less than what we currently test)

When we'll start to assess code coverage or when we'll start to get really thorough, it won't make sense to do all of our testing locally at all, and we might want to get some other metrics. For example, a major benefit is to automatically run tests on pull requests

It's free for open source project. Completely valid alternative would be Jenkins

https://docs.travis-ci.com/user/getting-started/

**Comment by kuzyn** [comment]
@aconanlai Should we include this in littleleague?

**Comment by aconanlai** [comment]
sure - i was going to to say we could discuss where we're at with testing, so this could be the direction to go in

**Comment by kuzyn** [comment]
d3e2300

Plugged through my account for now, but works well. Building and testing for node 7(latest), 6(latest) and 6.0

![screenshot from 2016-12-04 11-45-40](https://cloud.githubusercontent.com/assets/1139068/20867640/6b263c28-ba17-11e6-9415-c7b370f93100.png)
