### ISSUE TITLE
optimize backend for production

### ISSUE THREAD

**Issue by aconanlai** [n10as/n20.as#6]
https://devcenter.heroku.com/articles/optimizing-dyno-usage

https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node

https://devcenter.heroku.com/articles/node-best-practices

https://devcenter.heroku.com/articles/node-concurrency

**Comment by aconanlai** [comment]
http://stackoverflow.com/questions/11429774/how-to-communicate-web-and-worker-dynos-with-node-js-on-heroku

**Comment by aconanlai** [comment]
http://stackoverflow.com/questions/8426244/heroku-web-dyno-vs-worker-dyno-how-many-what-ratio-do-i-need

**Comment by kuzyn** [comment]
Possible solution for our `require(../../../../../what.ev)`

https://www.npmjs.com/package/app-module-path
https://gist.github.com/branneman/8048520

**Comment by aconanlai** [comment]
http://stackabuse.com/setting-up-a-node-js-cluster/

**Comment by aconanlai** [comment]
https://www.npmjs.com/package/sticky-session

**Comment by aconanlai** [comment]
hmm.. might be some work involved to run clustered socket.io, since node's cluster API won't pass off messages correctly to the other worker clusters... socket.io provides some solutions:

https://github.com/socketio/socket.io-redis

**Comment by aconanlai** [comment]
more links here, apparently the redis module is for node processes split across machines, but sticky-sessions is sufficient for clusters on a single machine:

https://github.com/socketio/socket.io-redis/issues/31

https://github.com/evilstudios/chat-example-cluster

https://github.com/elad/node-cluster-socket.io
