### ISSUE TITLE
user and session authentication

### ISSUE THREAD

**Issue by aconanlai** [n10as/n20.as#9]

**Comment by aconanlai** [comment]
https://github.com/auth0/node-jsonwebtoken

**Comment by aconanlai** [comment]
example react-router auth flow here: will be good to redirect to login page and maintain auth state:
https://github.com/ReactTraining/react-router/blob/master/examples/auth-flow/app.js

**Comment by aconanlai** [comment]
before we continue with implementation of authorization, i wanted to check it on our choice of auth flow: could you outline why we decided on oauth2? 
my understanding of 0auth2 is that its use case is APIs with external end users - i.e, the 0auth2 flow specifies Provider, Consumer and Client interactions - since there's no 'middle person' in our app, 0auth2 would work for us but might be beyond our needs. since we have a very well-defined set of auth/access needs (up to 10 users with chat privileges and read/write on our endpoints, a couple admins with read/write on the 'users' endpoint), my thought was that using a passport local or basic strategy with a sufficiently robust hashing system, and https would be secure, and reduce technical overhead (less boilerplate, less server requests for round trips, no need for Redis to store user session cache for the multiple handshakes)

if we do choose to go the oauth2 route, my understanding is that the grant type we want is the Client Credientials grant flow, since the 'user' doesn't need to 'grant access' to the app - we go straight from client to provider. 

http://docs.apigee.com/api-services/content/oauth-20-client-credentials-grant-type

thoughts?

**Comment by aconanlai** [comment]
although i'm still reading up on it, i'm still learning, would be open to either

this person has a ton of example repos for like every auth flow:
https://github.com/jaredhanson/passport-oauth2-client-password

**Comment by kuzyn** [comment]
> my thought was that using a passport local or basic strategy with a sufficiently robust hashing system, and https would be secure, and reduce technical overhead

Ah yeah I agree with all of that and actually pointed out that example merely as starting point for a passport implementation, rather than a choice of oauth. Should have been more explicit. (i.e. express scaffolding, models for our strategies, some kind of structure reference, what endpoints requirement to expects, etc). So even tho last night in chat I said it should be implemented, I guess I misspoke and was simply thinking in terms of functionalities after toying with it for 5 min

Like, immediate goal should be getting the simplest sort of authentication mechanism going and moving from there. But let me know what you have in mind, in term of an actual outline for implementation; you are certainly much more on the ball than me on this, since I have almost no time to research/read/compare

**Comment by kuzyn** [comment]
+ brings forth the needs to do 443 in express, which I'm sure is well documented but still something to take into account

**Comment by kuzyn** [comment]
okay actually trivial looking

**Comment by aconanlai** [comment]
ok so tonight my plan will be to implement the local/basic/bearer passport strategy, along with three routes/pages on the client:

/admin (the protected page)
/login (redirects here if user isn't logged in)
/logout (clears local storage and clears token from user in db

hopefully can get a fully working version tonight, but may go to sala rossa lol

**Comment by aconanlai** [comment]
actually i might try going straight to the facebook auth process tonight - since we need it for the events fetching

since the facebook developer API doesn't allow us to restrict access to certain users, we have to do the access control inside our `passport.use(new FacebookStrategy({}))` block - we'll store hashed facebook user ids and facebook access tokens in our db, and check for existence of them upon login

**Comment by aconanlai** [comment]
complete for now in https://github.com/n10as/n20.as/commit/2e923230424a869236c8d434d09f5500fe77bfe4 and preceding commits - still WIP though
